// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ig5ebWCmuseYJl3OV5f0O-AaCY3xa2U',
    appId: '1:23532912929:web:7c3f21e25475a397193e60',
    messagingSenderId: '23532912929',
    projectId: 'mpitfinal-161e4',
    authDomain: 'mpitfinal-161e4.firebaseapp.com',
    storageBucket: 'mpitfinal-161e4.appspot.com',
    measurementId: 'G-H54T93Y050',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mDVZzF34Ko_4ApELl0ffY-H4ctBDfdI',
    appId: '1:23532912929:android:66d96f6865e369d1193e60',
    messagingSenderId: '23532912929',
    projectId: 'mpitfinal-161e4',
    storageBucket: 'mpitfinal-161e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7cB2igWzU5YEGTRcx7x6mHQBvPyBBaS4',
    appId: '1:23532912929:ios:648a61b574624843193e60',
    messagingSenderId: '23532912929',
    projectId: 'mpitfinal-161e4',
    storageBucket: 'mpitfinal-161e4.appspot.com',
    iosBundleId: 'com.example.mpit2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7cB2igWzU5YEGTRcx7x6mHQBvPyBBaS4',
    appId: '1:23532912929:ios:9992d1773a134c11193e60',
    messagingSenderId: '23532912929',
    projectId: 'mpitfinal-161e4',
    storageBucket: 'mpitfinal-161e4.appspot.com',
    iosBundleId: 'com.example.mpit2023.RunnerTests',
  );
}
